openapi: 3.1.0
info:
  title: Pet Management API
  description: A Simple RESTful API for managing your pets.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
    description: 'Local Server'
  - url: 'https://api.example.com/api'
    description: 'Production Server'
paths:
  /users:
    post:
      summary: create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        201:
          description: user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UserResponse'
        409:
          description: username is already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: username already registered
  /users/login:
    post:
      summary: login using user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: success login
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: unique-token
        400:
          description: wrong credential
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: username or password is wrong
  /users/current:
    patch:
      summary: update user info
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        200:
          description: successfully update user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UserResponse'
        400:
          description: failed to update user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: name length max is 100
    get:
      summary: get current user info
      responses:
        200:
          description: user info retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UserResponse'
        401:
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: unauthorized
  /users/logout:
    delete:
      summary: logout from session
      responses:
        200:
          description: successfully logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: OK
        401:
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: unauthorized
components:
  schemas:
    UserInput:
      type: object,
      properties:
        username:
          type: string
          example: john123
        password:
          type: string
          example: password123
        name:
          type: string
          example: John
    UserResponse:
      type: object,
      properties:
        username:
          type: string
          example: john123
        name:
          type: string
          example: John
    LoginRequest:
      properties:
        username:
          type: string
          example: john123
        password:
          type: string
          example: password123
    UpdateUser:
      properties:
        name:
          type: string
          example: John
        password:
          type: string
          example: newpassword123
